### ISSUE TITLE
i64 arithmetic on JS?

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#22]
WebAssembly has a 64 bits float and integer type.

Even if we won't have interactions with >53bits integers between JavaScript code and the WebAssembly runtime (#21).

Our interpreter is still written in JavaScript and we need to handle it somehow, here's a few solutions:
- Emulate 64 bits arithmetic over 32 bits (what asm.js does)
    - We probably need a AST pass to tranform all i64 into i32.
- Compile your program with the 32 bits mode? Which adds a restriction to use our project.

---

asm.js does it already, here's are a few notes that I found:

- Unity in particular mentioned that emulation of 64-bit arithmetic in asm.js is really really slow

**Comment by maurobringolf** [comment]
Since JS uses IEEE double precision floating point numbers (64bit), f32 and f64 are no problem. Short integers i32 are no problem either, since they are representable with double precision doubles. The only type that requires extra handling is i64.

**Comment by alfonsogarciacaro** [comment]
Maybe long.js is an option? That's what Fable uses. https://github.com/dcodeIO/long.js

**Comment by xtuc** [comment]
Thanks @alfonsogarciacaro! That is looking good. Do you know how it affects Fable's performance?

I'm wondering if we could only apply this to numbers > 53bits, so that < 53bits number doesn't suffer from the overhead.

**Comment by alfonsogarciacaro** [comment]
We haven't measured but I guess we could run a bunch of operations with i32 and i64 numbers and see how they compare ([example](https://twitter.com/FableCompiler/status/890488515926122496)).

About discriminating numbers, it may be a bit difficult when you need to operate on them. For example, adding two <53 bits numbers that will result in a >53 bits number, etc.

**Comment by maurobringolf** [comment]
Im with @alfonsogarciacaro, I think the necessary logic to detect the need for >53 bit would produce more overhead and potential bugs than value. Performance will also be more predictable if all i64 values are affected the same way.

**Comment by xtuc** [comment]
Ok, that makes sense.

**Comment by maurobringolf** [comment]
Maybe this is too simplistic, but I just thought about this: For all nodes that hold `i64` values we store two values `lower` and `upper` and define its value as `lower + upper * 2^32`? Because these values are only internal to the wasm computation and cannot be passed in or out to host environment ( #21 ) we never need to represent the complete number in the interpreter. Instead of `+` we use a custom `add64` function that produces two values representing upper and lower.

Is that essentially what long.js would do for us or am I missing more benefits of using the library?

**Comment by xtuc** [comment]
Interesting https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/js-ctypes_reference/UInt64, but only on unsigned.

**Comment by maurobringolf** [comment]
That looks really good, basically the functions we need to implement in order to avoid long.js. But I think we'd need the signed version? I found something on his profile, but it looks like it is not done at all:

https://github.com/aureooms/js-int64

I don't see multiplication, division and remainder at all though?

**Comment by ColinEberhardt** [comment]
I'd vote for this solution too:

> For all nodes that hold i64 values we store two values lower and upper and define its value as lower + upper * 2^32

Having a simple representation like this means that we can easily change the operations implementations (e.g. possibly use long.js in the short term for more complex operations).

As I'm looking at bitwise operations, these are simple to implement on top of an `upper` / `lower` representation, so I'd just implement them directly.

Testing is going to be a bit of a challenge due to #21. I can see a couple of options:

1. Read / write to linear memory via store / load
2. Use bit shifting to allow checking of the upper / lower via i32 values. This would require implementation of `i64.shl`

I am guessing that (1) will require more work to introduce linear memory?

So for bitwise ops, I'd propose using (2) as a way to test

**Comment by xtuc** [comment]
Yes that's probably the best solution. 

FYI I have a test here #23 which returns an i32 so it's testable from js. Might be tedious to use tho. 

I believe we can play with the memory directly with store/load. The backend store is a simple js array. 

I would add a 3 solution, we can introduce a new type of test. I'm thinking about a stack inspector which could dump the whole memory as string. I guess it's better to test WebAssembly via itself?
